### ISSUE TITLE
Schema

### ISSUE THREAD

**Issue by pvulakh** [JaredDjour/InstaDjour#2]
Your schema's very thorough, good work! A couple of things:
### `photos` table: 
- [x] Let's remove the `photo_url` column. AWS will handle images for us, so we don't need to store them in our database
- [x] Consider renaming this table to `posts` as well, just so we're not dealing with code like `photo.photo` later on (when we end up referencing the image AWS supplied for us)
### `likes` table:
Users can like comments and photos, so our `likes` table will involve polymorphic associations. 
- [x] Let's add a `likeable_type` column and combine our `photo_id` and `comment_id` foreign keys to just be one column of `likeable_id`. Now `like` will belong to one database entry in either our `comments` or `photos` table. 
- [x] Modify the composite index to now be on `[ :user_id, :likeable_type, :likeable_id ]` so that a user can like a comment with an id of 1 as well as a photo with an id of 1. 

Let me know if you have questions on any of the above! Again, really good job on this :)

**Comment by JaredDjour** [comment]
Hey Polina, I made the edits to the photos table (now Posts table), but I'm confused as to what the Like table's likeable_type and likeable_id will do
