### ISSUE TITLE
Sample State

### ISSUE THREAD

**Issue by pvulakh** [JaredDjour/InstaDjour#3]
Really good work on this! A few tweaks: 

- [x] Add an array of `commentIds` in the `photos` slice of state
- [x] Add an array of `likingUsers` in the `comments` slice of state since `comments` can be liked as well 
- [x] Change all your keys to camelCase since this is JavaScript :) `liking_users` becomes `likingUsers`, etc

Let me know if you have any questions!

**Comment by JaredDjour** [comment]
I no longer have an image_url collum so how should i reference the images under each sample post?

**Comment by JaredDjour** [comment]
Also, the end of my sample state (with the ui, errors, and session keys) was copied from somewhere else--I don't know what they do
