### ISSUE TITLE
Backend Routes

### ISSUE THREAD

**Issue by pvulakh** [JaredDjour/InstaDjour#4]
Great work on these! A few things to modify: 
### `comments` routes:
- [x] Nest these under `photos`
- [x] Remove `:id` part of `POST comments` route since we're creating a comment. Only once that comment has been inserted into the database does its `id` exist
- [x] Add a `GET comments` route (still nested under `photos`) to get all of a photo's comments 
### `likes` routes:
- [ ] Nest `likes` routes under comments. Because of this double nesting (`comments` nested under `photos`, `likes` nested under `comments`), you're able to create likes for a photo OR a comment since you'll have access to both the `photo_id` and the `comment_id`
- [ ] Remove `:id` from `likes` create and delete. Because you won't have access to the `like` `id` when the user is deleting a `like`, we'll write a custom route for this once you're working on the `likes` MVP. 
### `follows` routes:
- [x] Nest `follows POST` and `DELETE` under `user` routes

Let me know if you have any questions about this!

**Comment by JaredDjour** [comment]
I'm not sure if I've nested them correctly, also -- I'm still confused as to how nested routes work. Does that mean I'll have a Like association to Posts 'through' Comments?
